version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: agentic-workflow-postgres
    environment:
      POSTGRES_DB: agentic_workflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    # No volumes - transient database for local testing
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d agentic_workflow"]
      interval: 10s
      timeout: 5s
      retries: 5

# No volumes needed - transient database