spring:
  # Test Database Configuration - uses Docker PostgreSQL
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/agentic_workflow}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  # Flyway configuration for tests
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: false # Allow clean in tests for fresh state

# Logging for tests
logging:
  level:
    dev.alsalman.agenticworkflowengine: DEBUG
    org.flywaydb: DEBUG
    org.springframework.jdbc: DEBUG