name: Test Coverage

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  actions: read
  pages: write

jobs:
  coverage:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: agentic_workflow
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'oracle'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Run tests with coverage
      env:
        SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/agentic_workflow
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres
      run: ./mvnw clean test jacoco:report

    - name: Create badges directory
      run: mkdir -p badges
      
    - name: Generate JaCoCo Badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v2.11.0
      with:
        generate-branches-badge: true
        jacoco-csv-file: target/site/jacoco/jacoco.csv
        badges-directory: badges
        
    - name: Log coverage percentage
      run: |
        echo "Coverage: ${{ steps.jacoco.outputs.coverage }}"
        echo "Branch coverage: ${{ steps.jacoco.outputs.branches }}"

    - name: Upload coverage badges
      uses: actions/upload-artifact@v4
      with:
        name: coverage-badges
        path: badges/*.svg
        if-no-files-found: error
        retention-days: 90
        
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: target/site/jacoco/
        if-no-files-found: error
        
    - name: Add coverage comment to PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const coverage = '${{ steps.jacoco.outputs.coverage }}';
          const branches = '${{ steps.jacoco.outputs.branches }}';
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `## Coverage Report
            - **Coverage**: ${coverage}%
            - **Branch Coverage**: ${branches}%`
          })
          
    - name: Publish badges to GitHub Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: badges
        branch: gh-pages
        clean: false